# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/richy/Projekte/BA/libavg_Plugin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/richy/Projekte/BA/libavg_Plugin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@echo "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@echo "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@echo "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@echo "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@echo "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@echo "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/richy/Projekte/BA/libavg_Plugin/CMakeFiles /home/richy/Projekte/BA/libavg_Plugin/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/richy/Projekte/BA/libavg_Plugin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named onitouch

# Build rule for target.
onitouch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 onitouch
.PHONY : onitouch

# fast build rule for target.
onitouch/fast:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/build
.PHONY : onitouch/fast

src/DepthTouchDetector.o: src/DepthTouchDetector.cpp.o
.PHONY : src/DepthTouchDetector.o

# target to build an object file
src/DepthTouchDetector.cpp.o:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/DepthTouchDetector.cpp.o
.PHONY : src/DepthTouchDetector.cpp.o

src/DepthTouchDetector.i: src/DepthTouchDetector.cpp.i
.PHONY : src/DepthTouchDetector.i

# target to preprocess a source file
src/DepthTouchDetector.cpp.i:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/DepthTouchDetector.cpp.i
.PHONY : src/DepthTouchDetector.cpp.i

src/DepthTouchDetector.s: src/DepthTouchDetector.cpp.s
.PHONY : src/DepthTouchDetector.s

# target to generate assembly for a file
src/DepthTouchDetector.cpp.s:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/DepthTouchDetector.cpp.s
.PHONY : src/DepthTouchDetector.cpp.s

src/OniDevice.o: src/OniDevice.cpp.o
.PHONY : src/OniDevice.o

# target to build an object file
src/OniDevice.cpp.o:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/OniDevice.cpp.o
.PHONY : src/OniDevice.cpp.o

src/OniDevice.i: src/OniDevice.cpp.i
.PHONY : src/OniDevice.i

# target to preprocess a source file
src/OniDevice.cpp.i:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/OniDevice.cpp.i
.PHONY : src/OniDevice.cpp.i

src/OniDevice.s: src/OniDevice.cpp.s
.PHONY : src/OniDevice.s

# target to generate assembly for a file
src/OniDevice.cpp.s:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/OniDevice.cpp.s
.PHONY : src/OniDevice.cpp.s

src/OniDeviceManager.o: src/OniDeviceManager.cpp.o
.PHONY : src/OniDeviceManager.o

# target to build an object file
src/OniDeviceManager.cpp.o:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/OniDeviceManager.cpp.o
.PHONY : src/OniDeviceManager.cpp.o

src/OniDeviceManager.i: src/OniDeviceManager.cpp.i
.PHONY : src/OniDeviceManager.i

# target to preprocess a source file
src/OniDeviceManager.cpp.i:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/OniDeviceManager.cpp.i
.PHONY : src/OniDeviceManager.cpp.i

src/OniDeviceManager.s: src/OniDeviceManager.cpp.s
.PHONY : src/OniDeviceManager.s

# target to generate assembly for a file
src/OniDeviceManager.cpp.s:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/OniDeviceManager.cpp.s
.PHONY : src/OniDeviceManager.cpp.s

src/OniDeviceThread.o: src/OniDeviceThread.cpp.o
.PHONY : src/OniDeviceThread.o

# target to build an object file
src/OniDeviceThread.cpp.o:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/OniDeviceThread.cpp.o
.PHONY : src/OniDeviceThread.cpp.o

src/OniDeviceThread.i: src/OniDeviceThread.cpp.i
.PHONY : src/OniDeviceThread.i

# target to preprocess a source file
src/OniDeviceThread.cpp.i:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/OniDeviceThread.cpp.i
.PHONY : src/OniDeviceThread.cpp.i

src/OniDeviceThread.s: src/OniDeviceThread.cpp.s
.PHONY : src/OniDeviceThread.s

# target to generate assembly for a file
src/OniDeviceThread.cpp.s:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/OniDeviceThread.cpp.s
.PHONY : src/OniDeviceThread.cpp.s

src/OniTouchPlugin.o: src/OniTouchPlugin.cpp.o
.PHONY : src/OniTouchPlugin.o

# target to build an object file
src/OniTouchPlugin.cpp.o:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/OniTouchPlugin.cpp.o
.PHONY : src/OniTouchPlugin.cpp.o

src/OniTouchPlugin.i: src/OniTouchPlugin.cpp.i
.PHONY : src/OniTouchPlugin.i

# target to preprocess a source file
src/OniTouchPlugin.cpp.i:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/OniTouchPlugin.cpp.i
.PHONY : src/OniTouchPlugin.cpp.i

src/OniTouchPlugin.s: src/OniTouchPlugin.cpp.s
.PHONY : src/OniTouchPlugin.s

# target to generate assembly for a file
src/OniTouchPlugin.cpp.s:
	$(MAKE) -f CMakeFiles/onitouch.dir/build.make CMakeFiles/onitouch.dir/src/OniTouchPlugin.cpp.s
.PHONY : src/OniTouchPlugin.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... onitouch"
	@echo "... rebuild_cache"
	@echo "... src/DepthTouchDetector.o"
	@echo "... src/DepthTouchDetector.i"
	@echo "... src/DepthTouchDetector.s"
	@echo "... src/OniDevice.o"
	@echo "... src/OniDevice.i"
	@echo "... src/OniDevice.s"
	@echo "... src/OniDeviceManager.o"
	@echo "... src/OniDeviceManager.i"
	@echo "... src/OniDeviceManager.s"
	@echo "... src/OniDeviceThread.o"
	@echo "... src/OniDeviceThread.i"
	@echo "... src/OniDeviceThread.s"
	@echo "... src/OniTouchPlugin.o"
	@echo "... src/OniTouchPlugin.i"
	@echo "... src/OniTouchPlugin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

